name: Build and Publish Package to S3
env:
  S3_BUCKET_NAME = "s3://aws-packages-vit/awsservice1/"
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2 # можна v3 - новіша версія   (node12 --> node16)

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: pip install twine setuptools # -r requirements.txt

      - name: Build Package
        run: python setup.py sdist bdist_wheel

      - name: Publish Package
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
#        env:
#          PACKAGE_VERSION: ${{ github.ref }}
#          PACKAGE_VERSION: ${{ env.GITHUB_REF#refs/tags/v }}
#          PACKAGE_VERSION: ${{ steps.version.outputs.version }}
        run: |
          aws s3 cp dist/*  env.S3_BUCKET_NAME
