name: Build-and-Publish-Package-to-S3
env:
  S3_BUCKET_NAME   : "s3://aws-packages-vit"
  AWS_REGION_NAME  : "us-east-1"
on:
  push:
    branches:
      - master

jobs:
  build_package_part:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2 # можна v3 - новіша версія   (node12 --> node16)

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Build Package (create new version of package)
        run: python setup.py sdist bdist_wheel
#  push_files_to_s3:
#    runs-on: ubuntu-latest
#    needs: [build_package_part]
#   НЕ РОЗДІЛЯЄМО, все видалиться - DELETED
#    steps:
      - name: Print directory content
        run : |
          ls -la
          ls -la dist/

      - name: Configure my AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id    :  ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region           :  ${{ env.AWS_REGION_NAME }}
    
      - name: Publish new Packages to S3 bucket with all versions
        run: |
          aws s3 cp dist/ s3://aws-packages-vit/awsservice1/ --recursive

      - name: Print Status Message
        run : echo "Function Updated Succesfully"
