name: Build-and-Publish-Package-to-S3
env:
  S3_BUCKET_NAME   : "s3://aws-packages-vit/awsservice1/"
  AWS_REGION_NAME  : "us-east-1" # Virginia
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2 # можна v3 - новіша версія   (node12 --> node16)

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: pip install twine setuptools # -r requirements.txt

      - name: Build Package
        run: python setup.py sdist bdist_wheel
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: env.AWS_REGION_NAME

      - name: Publish_Package
        run: |
          aws s3 cp dist/*  env.S3_BUCKET_NAME
          
      - name: Print Status Message 
        run : echo "Package Updated Succesfully"
