name: Build-and-Publish-Package-to-S3
env:
  S3_BUCKET_NAME   : "s3://aws-packages-vit/awsservice1/"
  AWS_REGION_NAME  : "us-east-1"
on:
  push:
    branches:
      - master

jobs:
  build_package_part:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2 # можна v3 - новіша версія   (node12 --> node16)

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Create directory Media/ ; create file_3 for running tests
        run : |
          mkdir media/
          touch ./media/file_3
          ls -la media/
          uname -a

      - name: Configure my AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id    :  ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region           :  ${{ env.AWS_REGION_NAME }}

      - name: Run tests
        run: python -m unittest tests/tests_s3service_moto.py

      - name: Build Package (create new version of package)
        run: python setup.py sdist bdist_wheel

      - name: Publish new Packages to S3 bucket with all versions
        run: |
          aws s3 cp dist/ ${{ env.S3_BUCKET_NAME }} --recursive

      - name: Print Status Message
        run : echo "Function Updated Succesfully"
